//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CREDITO = new HashSet<CREDITO>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string APEPAT { get; set; }
        public string APEMAT { get; set; }
        public string RUT { get; set; }
        public Nullable<System.DateTime> F_NAC { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string D_PART { get; set; }
        public string D_LAB { get; set; }
        public Nullable<int> SUELDO { get; set; }
    
        public virtual ICollection<CREDITO> CREDITO { get; set; }
    }
}
