//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int ID_FUNCIONARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APEPAT { get; set; }
        public string APEMAT { get; set; }
        public string RUT { get; set; }
        public Nullable<System.DateTime> F_NAC { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string TIPO { get; set; }
        public int ID_LOG { get; set; }
    
        public virtual INGRESO_LOGIN INGRESO_LOGIN { get; set; }
    }
}
